### PR TITLE
Hotfix TLSv1 support for mbed TLS

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by fmorgner** [comment]
I assume this is in relation to #90? I also assume, from the mumble roadmap, that mumble does not aim to release a "source" version with support for TLSv1.2/TLSv1.3 in the 1.2 mumble series. Is this assumption correct?

**Comment by l2dy** [comment]
Mumble 1.2.9 supports TLSv1.2, see https://wiki.mumble.info/wiki/1.2.9.

**Comment by fmorgner** [comment]
I saw that, but as I understand it, this only holds for the binary packages shipped by the mumble developers:

> The TLS 1.2 support in our binary packages is backported from Qt 5. Unfortunately, that means that if you are using Mumble from a package manager, you’re not going to get a TLS 1.2-enabled build.

**Comment by l2dy** [comment]
You're probably right.

**Comment by fmorgner** [comment]
On another note, does this patch still work with the 1.3 series of mumble? IIRC we had an issue a while back, where we had the problem that the 1.3 mumble series enforces good crypto. I can't recall from the top of my head if this was simply because of the suites, or if TLSv1 also had an influence.

**Comment by l2dy** [comment]
It's `min_version` so yes it still works.

**Comment by fmorgner** [comment]
missed that :)

**Comment by l2dy** [comment]
I suppose the mbedtls part of TLS upgrade came from l2dy@84ff6ec and I'd like to be in the list of contributors.

**Comment by mkrautz** [comment]
Just to clear things up:


# TLS 1.2 support in Mumble1.2.x

Support for TLS > 1.0 for Mumble 1.2.x packages depends on that particular distribution's Qt 4 package. The Qt project's latest Qt 4 release doesn't support TLS > 1.0.

Our own binary packages contain a patched Qt 4 that allows TLS 1.1 and TLS 1.2.

Some Mumble packagers, such as OpenBSD, also allow TLS 1.1 and TLS 1.2 for Mumble 1.2.x because their Qt 4 is patched.

Most Linux distros (if not all) only support TLS 1.0 with Qt 4.

# Stricter crypto in Mumble 1.3.x

For Mumble 1.3.x, we still allow TLS 1.0 clients to connect.
But in general, all packages support TLS 1.2, because Mumble 1.3.x for the most part is built against Qt 5.
It is, however, possible to build Mumble 1.3.x against Qt 4, in which case it will inherit the same TLS problems as Mumble 1.2.x has had. We don't expect Mumble 1.3.0 to be built against Qt 4 very often.

**Comment by fmorgner** [comment]
@mkrautz Thanks for clearing up the situation! So everything will work out.

**Pull request merged**
