### PR TITLE
Set stricter compiler flags

### PR DESCRIPTION
**Pull request by fmorgner**
There were some comparisons between signed and unsigned integers as
well as unused code and missing preprocessor defines. The new flags
helped finding those issues. There are still some open 'issues' marked
with 'TODO:', so simply grep using something like 'grep -r TODO: .'.
Some of the issues might be shortcomings of C, some might be fixable.

### CODE REVIEW

**Comment by doctaweeks** [comment]
-Werror should never be set in a build system. Warnings change over time and with compiler versions/variants.

At least the first type change in findFreeId is going to have a potentially unintended side-effect (INT_MAX vs UINT_MAX).

**Comment by fmorgner** [comment]
Totally missed that one. The id has to be uint32_t since, as far as i can tell, it is what we get from the code generated by protobuf. In src/Mumble.pb-c.h, all `channel_id`s are uint32_t. The same goes for some, if not all, of the other changes.

**Comment by fmorgner** [comment]
Found and fixed another occurence of the same problem. Additionally, maybe we should change the code to use UINT_MAX consistently throughout instead of using a casted -1 all over the place.

**Comment by fmorgner** [comment]
Closing in favor of #112.

**Pull request closed without merging**
