### PR TITLE
Update server.c

### PR DESCRIPTION
**Pull request by concatime**
Changed old link.

### CODE REVIEW

**Comment by omor1** [comment]
Simple change, and we've been using GitHub for quite a while; it makes no sense to continue pointing to the defunct Google Code repository. Does it make more sense to point to http://umurmur.net instead?

**Comment by concatime** [comment]
I don't recommend using the main website since:
1) No real https
2) We can loose the domain if the project stop being maintained

**Comment by concatime** [comment]
Please, this need to get merged!

**Comment by inklit** [comment]
This makes perfect sense to me. Google Code is defunct and shouldn't be used anymore anyways.

**Pull request merged**
